#pragma once
#include <stdint.h>

typedef enum
{
    PANIC_ID_NONE = 0,

    PANIC_ID_MAIN_NVS_FLASH_ERASE_FAILED,
    PANIC_ID_MAIN_NVS_FLASH_INIT_FAILED,
    PANIC_ID_MAIN_NVS_FLASH_INIT_FAILED2,
    PANIC_ID_MAIN_BT_CONTROLLER_MEM_RELEASE_FAILED,
    PANIC_ID_MAIN_BT_CONTROLLER_INIT_FAILED,
    PANIC_ID_MAIN_BT_CONTROLLER_ENABLE_FAILED,
    PANIC_ID_MAIN_BLUEDROID_INIT_FAILED,
    PANIC_ID_MAIN_BLUEDROID_ENABLE_FAILED,

    PANIC_ID_GATTCOMM_GAP_REGISTER_FAILED,
    PANIC_ID_GATTCOMM_GATTS_REGISTER_FAILED,
    PANIC_ID_GATTCOMM_GATTS_APP_REGISTER_FAILED,
    PANIC_ID_GATTCOMM_SET_LOCAL_MTU_FAILED,
    PANIC_ID_GATTCOMM_ADV_START_FAILED,
    PANIC_ID_GATTCOMM_ADV_START_FAILED2,
    PANIC_ID_GATTCOMM_GATTS_REG_EVT_FAILED,
    PANIC_ID_GATTCOMM_SET_DEVICE_NAME_FAILED,
    PANIC_ID_GATTCOMM_CONFIG_ADV_DATA_FAILED,
    PANIC_ID_GATTCOMM_CONFIG_SCAN_RSP_DATA_FAILED,
    PANIC_ID_GATTCOMM_CREATE_SERVICE_FAILED,
    PANIC_ID_GATTCOMM_START_SERVICE_FAILED,
    PANIC_ID_GATTCOMM_ADD_CHAR_FAILED,

    PANIC_ID_LEDMGR_LEDC_TIMER_CONFIG_FAILED,
    PANIC_ID_LEDMGR_LEDC_CHANNEL_CONFIG_FAILED,
    PANIC_ID_LEDMGR_CREATE_QUEUE_FAILED,
    PANIC_ID_LEDMGR_TASK_CREATE_FAILED,
} panic_id_t;

__attribute__((noreturn)) void panic(panic_id_t id);

void app_on_gatt_connected(void);
void app_on_gatt_disconnected(void);
void app_on_gatt_rx(const uint8_t *data, uint16_t length);

void app_on_spp_connected(void);
void app_on_spp_connect_error(void);
void app_on_spp_disconnected(void);
void app_on_spp_rx(const uint8_t *data, uint16_t length);
